# -*- python -*-
Import("env")
import re, os, glob
import lsst.tests

thisPkg    = env.thisPkg
pythonPkg  = env.pythonPkg
pythonPath = env.pythonPath


###############################################
# specify dependencies for cc source code
thisLib = os.path.join("..", "lib", "lib"+thisPkg+env['LDMODULESUFFIX'])
for fileName in glob.glob("*.cc"):
    env.Depends(fileName, thisLib)
    env.Program(fileName, LIBS=env.getlibs(thisPkg))

###  Tests  ###
tests = lsst.tests.Control(env, ignoreList=[], expectedFailures={})
tests.run("*.cc")

pythonLib = os.path.join("..", pythonPath, "_"+pythonPkg+"%s" % env['LDMODULESUFFIX'])

for target in tests.run("*.py"):
    env.Depends(target, pythonLib)


